#!/bin/sh
node /Users/jeff.rynhart/Dev/Projects/exhibits-app/client/exhibits-frontend.js --node-args="--max-old-space-size=6096" > /Users/jeff.rynhart/Dev/Projects/exhibits-app/client/exhibits-frontend.log
