<svelte:head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</svelte:head>

<script>
    import Item_Grid_Vertical_Timeline from '../../templates/partials/Item_Grid_Vertical_Timeline.svelte';

    let grid = {
      "uuid": "79e82ffbc8990ab4d03255707f3b1527",
      "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
      "type": "vertical_timeline",
      "title": "<div style=\"color: #8b2332\">Mascots, Nicknames, and Resistance timeline (1860 - 2020)</div>",
      "text": "This timeline includes major events (1864-2008) in University of Denver history related to its history with Native Americans (including but not limited to the Cheyenne and Arapaho nations), settler colonialism, and our mascots and nicknames. This timeline is not inclusive or reflective of all logo and branding changes during the University's history.",
      "order": 1,
      // "styles": "{\"backgroundColor\":\"#E3DCC2\"}",
      "styles": {
        "backgroundColor":"#E3DCC2"
      },
      "items": [
        {
          "uuid": "57b325a7f779a5ad1558340205e052ab",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1864-03-05T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">MARCH 5, 1864</div>",
          "description": "University of Denver was founded by John Evans, also Colorado's Second Territorial Governor.",
          "caption": "Image: Portrait of John Evans between 1880-1897. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "57b325a7f779a5ad1558340205e052ab.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 1        
        },
        {
          "uuid": "8119b5f5a23193bc59bf60882a3e889e",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1864-11-29T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">NOVEMBER 29, 1864</div>",
          "description": "Sand Creek Massacre. More than 160 Cheyenne and Arapaho people - primarily women, children, and elders - are massacred by the Colorado Third Cavalry, led by DU trustee Colonel John Chivington.",
          "caption": "\"One November Morning\" by Brent Learned, 2014. Courtesy of Brent Learned.",
          "item_type": "image",
          "media": "8119b5f5a23193bc59bf60882a3e889e.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 2        
        },
        {
          "uuid": "ed099cd4004d2ca5a4a747a72c800ae2",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1919-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">1919</div>",
          "description": "The \"Fighting Parsons\" is first mentioned as a nickname for the football team in the Clarion. No likeness or cartoon associated with the nickname; the team is also called \"Fighting Ministers.\"",
          "caption": "\"One November Morning\" by Brent Learned, 2014. Courtesy of Brent Learned.",
          "item_type": "image",
          "media": "ed099cd4004d2ca5a4a747a72c800ae2.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 3        
        },
        {
          "uuid": "77d4137d354ae026bb023b9fa081598e",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1924-10-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 1924</div>",
          "description": "Clarion article \"Denver ‘Battling Ministers’ Seek Fitting Name: War Cry to Replace Outworn Slogans is Big Contest Aim\" highlights student desire to change nickname to something that better reflects the school mission and spirit.",
          "caption": "\"Denver 'Battling Ministers' Seek Fitting Name: War Cry to Replace Outworn Slogans is Big Contest Aim\" Article in the Denver Clarion vol. 29, no. 6, October 23, 1924. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "77d4137d354ae026bb023b9fa081598e.jpg",
          "text": "",
          "thumbnail": "",
          "layout": "right",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 4        
        },
        {
          "uuid": "0a1577c13dbc91442ad563be0f3be928",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1925-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">1925</div>",
          "description": "Pioneers first mentioned in 1924-25 (vol 27) Kynewisbok, the student yearbook; in subsequent years (such as this image from the 1925-26 yearbook), the University added a \"Pioneer Day\" to their Homecoming celebrations, where faculty, students, and staff would dress in 1890s costume, often with white students in costume as Native Americans.",
          "caption": "\"Y.M./Y.W. Pioneer Rally\" Image from 1925-26 Kynewisbok. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "0a1577c13dbc91442ad563be0f3be928.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 5        
        },
        {
          "uuid": "e4d7eab69954844dc2c5b767ff7dd60b",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1950-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">1940S AND 1950S</div>",
          "description": "\"Pioneer Pete\" character appears first as illustrations and then as a mascot-type in the 1950s. \"Pioneer Pete\" was a person in costume who appeared at football games.",
          "caption": "Image of \"Pioneer Pete\" from 1956-1957 Kynewisbok yearbook. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "e4d7eab69954844dc2c5b767ff7dd60b.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 6        
        },
        {
          "uuid": "e366566d5444cfd8e74e5e57c67b497e",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1960-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">1960</div>",
          "description": "DU football team and program dissolved; Pioneer Pete character does not appear again.",
          "caption": "\"No More Football\" masthead from January 10, 1961, volume 37, no 22. Courtesy of DU Special Collections and Archives.",
          "item_type": "pdf",
          "media": "e366566d5444cfd8e74e5e57c67b497e.pdf",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 7      
        },
        {
          "uuid": "dad70c0a4e9ff51fa838c6d03488fa17",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1968-10-02T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 2, 1968</div>",
          "description": "Denver Boone first introduced as a cartoon in The Clarion, in an article called \"DU's New Pioneer Needs a Name.\"",
          "caption": "\"DU's New Pioneer Needs a Name\" from October 2 1968 University of Denver Clarion. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "dad70c0a4e9ff51fa838c6d03488fa17.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 8     
        },
        {
          "uuid": "8d6a19a529125f1f7a944cdc42ffb4c1",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1968-10-23T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 23, 1968</div>",
          "description": "Student Steve Kiley is the contest winner with the name \"Denver Boone.\" Per Kiley, \"We were boozing it up at a party when we decided on the name.\"",
          "caption": "\"Denver Boone to Help Eliminate Mascot Identity Problem\" in October 23, 1968 Clarion. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "8d6a19a529125f1f7a944cdc42ffb4c1.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 9       
        },
        {
          "uuid": "53c475922d3d1e68ddca7039c9bdeb0a",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1984-09-17T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">SEPTEMBER 17, 1984</div>",
          "description": "University administrators propose beginning to phase out Denver Boone due to \"male gender stereotyping and its specifically western symbolism.\"",
          "caption": "\"DU's PR Reviews Image of Boone, New Logo to Phase Out Old Mascot\" in September 17 1984 Clarion. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "53c475922d3d1e68ddca7039c9bdeb0a.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 10        
        },
        {
          "uuid": "22ea0c2d0383bb3c251f2a92304a57e6",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1999-09-04T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">SEPTEMBER 4, 1999</div>",
          "description": "Chancellor Dan Ritchie teases the unveiling of a \"new friend and companion\" for Denver Boone. The Clarion author is careful to note \"the move is not an effort to exclude Boone from DU, but a hope that a new mascot will bring new life and vitality and become a new leader in spirit.\"",
          "caption": "\"New Mascot to Be Unveiled\" Clarion article September 4th, 1999. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "22ea0c2d0383bb3c251f2a92304a57e6.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 11       
        },
        {
          "uuid": "d94eea928db27bc7b55d0b2875fee94d",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "1999-09-08T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">SEPTEMBER 8, 1999</div>",
          "description": "A mascot character named \"Ruckus\" is unveiled as the new mascot. Originally named \"Rufus Clark\" after the landowner who donated the land for the University Park campus, Ruckus is a red-tailed hawk with a cowboy hat and a scarlet-colored vest. The vest is a reference to the \"chancellor's red vest,\" a tradition going back to Chancellor Henry Augustus Buchtel (1900-1920).",
          "caption": "\"Ruckus\" at Homecoming Barbecue, between 1998-2008. Courtesy of DU Special Collections and Archives.",
          "item_type": "image",
          "media": "d94eea928db27bc7b55d0b2875fee94d.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 12       
        },
        ////////////
        // complete
        ////////////
        {
          "uuid": "33abf2863e5a5d389eecfa014306c445",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2008-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">2005 - 2008</div>",
          "description": "Students (primarily student-athletes) informally advocate to \"Bring Back Boone.\" Hockey goalie Peter Mannino and several other hockey players during this period play with \"Boone\" stickers on their helmets. In May 2008, students create a \"Bring Back Boone\" video (see screenshot) featuring primarily student-athletes as well as some DU faculty and staff.",
          "caption": "Screenshot, \"Bring Back Boone\" Student-Created Video, 2008",
          "item_type": "image",
          "media": "33abf2863e5a5d389eecfa014306c445.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 13
        },
        {
          "uuid": "cc27482e5eb49479bca4b37ff00e1848",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2008-10-20T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 20, 2008</div>",
          "description": "Chancellor Robert Coombe sends a campus-wide e-mail with the phrase \"The Denver Boone figure is one that does not reflect the broad diversity of the DU community and is not an image that many of today's women, persons of color, international students and faculty, and others can easily relate to as defining the pioneering spirit....One thing is certain--we will always be the Pioneers.\" Coombe releases the \"Boone\" image to be used by students and alumni \"as a celebration of the past...to the extent that they may wish.\"",
          "caption": "\"Ruckus\" at Homecoming Barbecue, between 1998-2008",
          "item_type": "image",
          "media": "cc27482e5eb49479bca4b37ff00e1848.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 14      
        },
        {
          "uuid": "d79c62ebc2ee3289cd13277e48ff7b6f",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2009-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">2009</div>",
          "description": "Alumni, students, and community members fundraise $8,000 to fund an \"unofficial\" Boone mascot costume and pay the mascot to attend DU sporting and other events. Per alum Damien Goddard, class of 1988 and originator of the LetsGoDU website, \"We kept hoping that the University of Denver would reconsider its decision in the fall to mothball Boone...when it became obvious that no amount of letter writing, e-mails or public relations would change the decision, we changed our tactics.\"",
          "caption": "Photo of the new \"Denver Boone\" mascot costume funded by DU Alumni in 2009.",
          "item_type": "image",
          "media": "d79c62ebc2ee3289cd13277e48ff7b6f.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 15    
        },
        {
          "uuid": "36f03598cb7ab6e47b2c55f783b374d7",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2011-05-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">MAY 2011</div>",
          "description": "The University of Denver holds its first annual Pow Wow. Viki Eagle (DU BA, MA), later the first Director of Native American Community Outreach and Partnerships, plays an integral role in organizing the Pow Wow, Elder Dinner, and the Native Student Alliance during her time as a student.",
          "caption": "Photo of dancers during the 2011 Spring Pow Wow at the University of Denver.",
          "item_type": "image",
          "media": "36f03598cb7ab6e47b2c55f783b374d7.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 16  
        },
        {
          "uuid": "f65dae10a97ff14248cbd5d209ff21fe",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2012-04-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">APRIL 2012</div>",
          "description": "Lamda Chi Alpha and Delta Delta Delta hold “Cowboys and Indians” party and later apologize to Native Student Alliance (NSA). ",
          "caption": "Photo of Lambda Chi Alpha fraternity house",
          "item_type": "image",
          "media": "f65dae10a97ff14248cbd5d209ff21fe.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 17
        },
        {
          "uuid": "420e7eea51d5814ebf4e4d34f9b1b181",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2013-02-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">FEBRUARY 2013</div>",
          "description": "Denver Boone filmed in YouTube video for \"Harlem Shake.\" Three Native Student Alliance (NSA) members Jose Guerrero, Amanda Wilson, and Julia Bramante protest Denver Boone being in a public video representing the University and were removed from the area by Campus Safety.",
          "caption": "Still from the \"Harlem Shake (University of Denver version)\" YouTube video, uploaded February 15, 2013.",
          "item_type": "image",
          "media": "420e7eea51d5814ebf4e4d34f9b1b181.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 18
        },
        {
          "uuid": "e75694b7dcc4fa137d3ee36df32045b5",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2013-03-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">MARCH 2013</div>",
          "description": "Undergraduate Student Government (USG) passes resolution to pull funding for any student organization that uses allocated funds to purchase merchandise that depicts the “Boone” character. This was paired with the expectation that a new mascot would be chosen by the committee that several USG members sat on.",
          "caption": "\"Denver Boone\" cartoon.",
          "item_type": "image",
          "media": "e75694b7dcc4fa137d3ee36df32045b5.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 19
        },
        {
          "uuid": "d7a6f5bd80cf063a33ac925160ca7ac9",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2013-08-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">MARCH-AUGUST 2013</div>",
          "description": "Three potential mascots revealed after (March-June) research process, a survey was sent out to choose the new mascot. Survey found \"no consensus\” on new mascot; 70% would be receptive or neutral on a new mascot but did not coalesce around the options presented – a jackrabbit, an elk, or a mountaineer.",
          "caption": "Graphic of three potential new mascots for DU",
          "item_type": "image",
          "media": "d7a6f5bd80cf063a33ac925160ca7ac9.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 20
        },
        {
          "uuid": "1816949e04d902746324fd66de077233",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2014-11-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">NOVEMBER 2014</div>",
          "description": "John Evans Study Committee (convened in 2013) issues its report on the Sand Creek Massacre, finding John Evans (founder of the University of Denver and Second Territorial Governor) complicit in the massacre.",
          "caption": "Front cover of the \"Report of the John Evans Study Committee University Of Denver.\"",
          "item_type": "image",
          "media": "1816949e04d902746324fd66de077233.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 21
        },
        {
          "uuid": "6db40678cbf0dfdc297780ca07e26dc8",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2016-05-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">MAY 2016</div>",
          "description": "Task Force on Native American Inclusivity issues report, including the language: \"The Task Force is unanimous in its belief that more work needs to be done to eliminate the presence of Boone from the DU campus and official University events.\”",
          "caption": "Unofficial \"Denver Boone\" mascot in a stairwell at Magness Arena.",
          "item_type": "image",
          "media": "6db40678cbf0dfdc297780ca07e26dc8.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 22
        },
        {
          "uuid": "6a33dba349e42a3187fa377bcddd19e5",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2016-10-14T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 14, 2016</div>",
          "description": "A multiracial coalition of students, staff, and faculty, including members of multiple racial affinity student groups, issue a list of demands related to racial equity on campus, including: \"Charge MarComm to create and implement a more representative mascot,\" \"elimination of Boone's presence\" at DU and noting that \"the term \"pioneer\" is highly problematic for many, especially our Native American students, as it is defined as a person who is among the first to explore or settle a new country or area.\"",
          "caption": "Student list of demands October 2016",
          "item_type": "pdf",
          "media": "6a33dba349e42a3187fa377bcddd19e5.pdf",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 23
        },
        {
          "uuid": "caa32742b7c272af19b15218c04376fc",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2017-10-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">OCTOBER 2017</div>",
          "description": "Native Student Alliance (NSA) launches #NoMorePios campaign. Image from March 2, 2018 direct action at a University of Denver's hockey game. April-May  2019, Clarion Executive Editor Grace Carson (Diné) publishes a 5-part series \"DU While Native.\" (images + links courtesy Grace Carson)",
          "caption": "#NoMorePios Banner",
          "item_type": "image",
          "media": "caa32742b7c272af19b15218c04376fc.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 24
        },
        ////////////
        // complete
        ////////////
        {
          "uuid": "f30b0a9c40668b49a67b0d784b7d77dc",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2018-01-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">JANUARY 2018</div>",
          "description": "\"Unofficial\" Boone mascot banned from DU athletics events, citing Board of Trustees' no-mask policy as justification.",
          "caption": "Unofficial Boone Mascot Poses at the 2012 Presidential Debate Held at the University of Denver",
          "item_type": "image",
          "media": "f30b0a9c40668b49a67b0d784b7d77dc.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 25
        },
        {
          "uuid": "c59e55e43496b9ad8bf81a3b67d03c47",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2018-04-01T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">APRIL 2018</div>",
          "description": "In recognition of the tribal sovereignty and original homelands of the Northern Cheyenne, Northern Arapaho and Southern Cheyenne and Arapaho Nations, their flags are hung in Driscoll North, alongside the flags of the United States, state of Colorado, and the University of Denver flag.",
          "caption": "Representatives from Northern Cheyenne, Northern Arapaho and Southern Cheyenne and Arapaho nations hold flags during a ceremony to hang them in the University of Denver Driscoll Student Center.",
          "item_type": "image",
          "media": "c59e55e43496b9ad8bf81a3b67d03c47.png",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 26
        },
        {
          "uuid": "7122c66abe6e0a43453ccc227a2029b5",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2019-11-04T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">NOVEMBER 4, 2019</div>",
          "description": "For Native American Heritage Month, the Native Student Alliance develops a \"No Stolen Sisters\" event and exhibit in the Anderson Academic Commons. The exhibit draws attention to Missing and Murdered Indigenous Women and Girls (often seen as the social media hashtags #MMIW and #MMIWG). The event included red dresses hung in the atrium of the Anderson Academic Commons, a drum circle, and speakers from the NSA and community members.",
          "caption": "\"No More Stolen Sisters\" Exhibit",
          "item_type": "image",
          "media": "7122c66abe6e0a43453ccc227a2029b5.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 27
        },
        {
          "uuid": "5756a7a16134dfbaccd752418e923c9d",
          "is_member_of_exhibit": "cd1c36f45f1fa9e80b060ea9e893bab6",
          "date": "2020-09-25T00:00:00",
          "title": "<div style=\"color: #8b2332; text-align: center\">SEPTEMBER 25, 2020</div>",
          "description": "Righteous Anger, Healing Resistance (RAHR), a multiracial coalition of students, held a protest related to their list of demands, which includes #NoMorePios. Full list: the establishment of a Critical Race and Ethnic Studies (CRES) department, engagement with Native communities through scholarships, mentorship programs, etc., reconstitution of the Native American Advisory Board, increased hiring and retention of faculty of color, divestment from any and all ties with ICE, and a seat for students on the Board of Trustees.",
          "caption": "\"No More Pios\" sign",
          "item_type": "image",
          "media": "5756a7a16134dfbaccd752418e923c9d.jpg",
          "text": "",
          "thumbnail": "",
          "type": "item",
          "styles": "{}",
          "is_published": 0,
          "order": 28
        }
      ],
      "is_published": 0
    }
</script>

<div class="test">
    <Item_Grid_Vertical_Timeline {grid} />
</div>

<style>
    .label {
        text-align: center;
    }

    .test {
        border-style: none;
    }
</style>